// ==UserScript==
// @name         Auto Skip Intro
// @namespace    http://tampermonkey.net/
// @version      2025-02-09
// @description  Skip it!
// @author       Zane Reisbig
// @match        https://app.plex.tv/desktop/
// @icon         https://www.google.com/s2/favicons?sz=64&domain=plex.tv
// @grant        none
// ==/UserScript==

(function () {
    "use strict";

    // Generated By Create New Playground
    // Generated At: 2025-02-10 00:13:52.533946
    // Author: Zane Reisbig

    const TIME = {
        SECOND: 1000,
        MINUTE: 1000 * 60,
        HOUR: 1000 * 60 * 60,
    };

    const CONFIG = {
        WAIT_BEFORE_CLICK_DELAY: TIME.SECOND * 5, // Default 5 Seconds
        AFTER_CLICK_COOLDOWN: TIME.MINUTE, // Default 1 Minute
    };

    const sleep = async (delayMS: number) => {
        return new Promise((res) => {
            setTimeout(() => res(true), delayMS);
        });
    };

    const elementFound = async <T>(selector: string) => {
        let iter = 0;

        return new Promise<T>(async (res) => {
            let found = document.querySelector(selector);

            while (found == null) {
                if (iter % 100 === 0) {
                    console.log("Keep Alive From - ELEMENT FOUND BODY");
                }

                found = document.querySelector(selector);
                await sleep(20);
                iter = iter + 1;
            }

            res(found as T);
        });
    };

    const selectorClassList = [
        "AudioVideoFullPlayer-overlayButton-D2xSex",
        "Button-button-TxWeuE",
        "Link-link-SxPFpG",
        "Button-default-sxqP0M",
        "Button-large-mFYLSo",
        "Link-default-BXtKLo",
    ];

    const main = async () => {
        while (true) {
            const skipIntro = await elementFound<HTMLButtonElement>(
                "button." + selectorClassList.join(".")
            );

            // A little delay to hear the intro start to play
            // Also because sometimes the intro detection is a little off
            // Adjust to your liking
            await sleep(CONFIG.WAIT_BEFORE_CLICK_DELAY);

            skipIntro.click();

            await sleep(CONFIG.AFTER_CLICK_COOLDOWN);
            console.log("\n\n\n\n--- SKIPPER RE-ACTIVATED ---\n\n\n");
        }
    };

    main();
    console.log("\n\n\n\n--- INTRO SKIPPER CALLED ---\n\n\n");
})();
